[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_vrf = "FNakiWan2eG3uq3sAKPw2a8UraACS62NWmq822EVNH7T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/parsa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
