[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_vrf = "3YkYBxgwExNqQm1ZSGNJsMuYDD9pC9NM3dmRfohqv3LA"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/parsa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
